# Backend API and worker share this image (different command in compose).
# Build from repository root: docker build -t edgar-backend .

FROM python:3.12-slim-bookworm

WORKDIR /app

ENV PYTHONPATH=/app \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Install deps before copying source for better layer caching.
# requirements.lock is the fully-pinned runtime set (generated by scripts/compile-requirements.sh).
COPY requirements.lock ./
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.lock

COPY backend ./backend
COPY edgar_project ./edgar_project
COPY agentic ./agentic
COPY src ./src
COPY config.py ./
COPY alembic ./alembic
COPY alembic.ini ./
COPY tests/__init__.py ./tests/__init__.py
COPY tests/support ./tests/support
# Operator tooling that has to run *inside* the deployed stack: recording a demo writes
# artifact blobs to the container's artifact volume, so it cannot be run from a laptop against
# the production database — the rows would point at object keys that exist nowhere.
# See docs/deploy.md step 4.
COPY scripts ./scripts
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh \
    && useradd --create-home --shell /bin/bash --uid 1000 appuser \
    && chown -R appuser:appuser /app

# Drop privileges after fixing artifact volume permissions (see entrypoint).
USER root
ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 8000
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
