// Generated by scripts/export_demo_static.py — do not edit by hand.
import type { InvestigationDetail, InvestigationSummary } from "@/lib/api/types";

import artifactHrefs from "./artifacts.json";
import index from "./index.json";
import detail0 from "./csv-delivery-delays.json";
import detail1 from "./edgar-margin-vs-growth.json";

export const DEMO_INDEX = index as unknown as InvestigationSummary[];

export const DEMO_DETAILS: Record<string, InvestigationDetail> = {
  "csv-delivery-delays": detail0 as unknown as InvestigationDetail,
  "edgar-margin-vs-growth": detail1 as unknown as InvestigationDetail,
};

export const DEMO_ARTIFACT_HREFS: Record<string, Record<string, string>> =
  artifactHrefs as Record<string, Record<string, string>>;
